services:
  - type: web
    name: calvary-prema-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
      - key: CLIENT_ORIGIN
        sync: false
      - key: FIREBASE_PROJECT_ID
        value: calvaryprema-9ed2d
      - key: FIREBASE_CLIENT_EMAIL
        sync: false
      - key: FIREBASE_PRIVATE_KEY
        sync: false
